"""student id and notes

Revision ID: bfa0ce4ad9e1
Revises: e944222de3d8
Create Date: 2020-11-22 03:18:01.431967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa0ce4ad9e1'
down_revision = 'e944222de3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('User', sa.Column('studentId', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'studentId')
    op.drop_column('User', 'notes')
    # ### end Alembic commands ###
