"""Added status field to User model

Revision ID: e944222de3d8
Revises: 12e380bba168
Create Date: 2020-11-21 20:01:12.690698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e944222de3d8'
down_revision = '12e380bba168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'status')
    # ### end Alembic commands ###
